(feat): Adding all openebs experiments in e2e pipeline
openebs/e2e-packet pull request #113
Opened 2020-02-04 13:05 UTC by shubhamchaudhary

Signed-off-by: shubhamchaudhary <shubham.chaudhary@mayadata.io>

2020-02-04 15:58 UTC, uditgaurav commented
Can we put all the experiments in one folder in place of placing it in different folders? Also, add the Pipeline link when you get it. Otherwise, it looks good to me. Thanks @shubhamchaudhary 
cc: @ksatchit

2020-02-04 19:11 UTC, uditgaurav approved these changes
lgmt

2020-02-05 02:44 UTC, somesh2905 requested changes

2020-02-05 02:44 UTC, somesh2905 commented on script/chaoscharts/Pool-Container-Failure/pool-container-failure
> +bash script/utils/e2e-cr jobname:pool-container-failure jobphase:Waiting init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag"
Implement pooling logic here

2020-02-05 02:44 UTC, somesh2905 commented on script/chaoscharts/Pool-Pod-Failure/pool-pod-failure
> +bash script/utils/e2e-cr jobname:pool-pod-failure jobphase:Waiting init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag"
Implement pooling logic here

2020-02-05 02:44 UTC, somesh2905 commented on script/chaoscharts/Target-Container-Failure/target-container-failure
> +bash script/utils/e2e-cr jobname:target-container-failure jobphase:Waiting init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag"
Implement pooling logic here

2020-02-05 02:44 UTC, somesh2905 commented on script/chaoscharts/Target-Network-Delay/target-network-delay
> +bash script/utils/e2e-cr jobname:target-network-delay jobphase:Waiting init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag"
Implement pooling logic here

2020-02-05 02:44 UTC, somesh2905 commented on script/chaoscharts/Target-Network-Loss/target-network-loss
> +bash script/utils/e2e-cr jobname:target-network-loss jobphase:Waiting init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag"
Implement pooling logic here

2020-02-05 02:44 UTC, somesh2905 commented on script/chaoscharts/Target-Network-Loss/target-network-loss
> +kubectl apply -f result-target-network-delay.yml; exit 1
kubectl apply -f result-target-network-loss.yml

2020-02-05 02:48 UTC, somesh2905 commented
@shubhamchaudhary Please add all the experiments in .gitlab-ci . So that they can execute in pipeline.

2020-02-05 10:01 UTC, somesh2905 approved these changes
lgtm

2020-02-06 08:08 UTC, nsathyaseelan approved these changes
lgtm

2020-02-06 08:08 UTC, merged