add(script): Added gitlab script for cstor csi snapshot and clone test cases
openebs/e2e-packet pull request #114
Opened 2020-02-07 07:33 UTC by w3aman

Signed-off-by: Aman Gupta <aman.gupta@mayadata.io>
Gitlab runner scrippt added for following test cases

- cspc-striped-pool
- csi-provisioner
- csi-snapshot
- csi-clone

2020-02-07 07:41 UTC, somesh2905 requested changes

2020-02-07 07:41 UTC, somesh2905 commented on script/2-infra-setup/deploy-csi-provisioner/csi-provisioner
> +${utils_path}/setup_dependencies infra-setup
modify dependency to litmus test

2020-02-07 07:41 UTC, somesh2905 commented on script/3-functional/csi-cstor-clone/csi-cstor-clone
> +${utils_path}/setup_dependencies infra-setup
modify dependency to litmus test

2020-02-07 07:42 UTC, w3aman commented on script/2-infra-setup/deploy-csi-provisioner/csi-provisioner
> +${utils_path}/setup_dependencies infra-setup
Done

2020-02-07 07:43 UTC, w3aman commented on script/3-functional/csi-cstor-clone/csi-cstor-clone
> +${utils_path}/setup_dependencies infra-setup
Done

2020-02-07 07:55 UTC, somesh2905 requested changes

2020-02-07 07:55 UTC, somesh2905 commented on script/3-functional/csi-cstor-snapshot/csi-cstor-snapshot
> +${utils_path}/setup_dependencies infra-setup
modify dependency to litmus test

2020-02-07 07:56 UTC, somesh2905 commented
/lgtm

2021-07-12 05:49 UTC, w3aman commented
Not required further...
closing

2021-07-12 05:49 UTC, closed without merging